export const issueExplanations: Record<string, string> = {
    KnownPhishingDomain: "This domain appears in public phishing databases.",
    NumbersInDomain: "Numbers in domains may mimic legitimate brands (e.g., g00gle).",
    ExcessiveSubdomains: "Many subdomains can indicate URL obfuscation.",
    SpecialCharacters: "Suspicious characters are often used in phishing URLs.",
    DomainTooNew: "Recently registered domains are common in scams.",
    DDNSDetected: "Dynamic DNS services are often abused for phishing.",
    NoSSLCertificate: "No SSL may mean the site isn't secure.",
    ExpiredSSLCertificate: "An expired certificate indicates neglect or malicious intent.",
    WeakSSLIssuer: "Self-signed or free CAs are common in phishing.",
    SSLConnectionError: "SSL could not be validated.",
    TooManyRedirects: "Phishing chains often involve many redirects.",
    InsecureRedirect: "Downgrade from HTTPS to HTTP is suspicious.",
    CrossDomainRedirect: "Redirection across unrelated domains may be a phishing tactic.",
    SimilarToKnownDomain: "Domain is visually similar to a trusted one (typosquatting).",
    LoginFormDetected: "Fake login forms are common phishing strategies.",
    SensitiveFieldDetected: "Asking for SSNs or credit card info is suspicious.",
    FormDetected: "Forms on the page may be used to collect sensitive data.",
};
